// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");

function encodeRequestMethod(requestMethod) {
  if (typeof requestMethod === "object") {
    return requestMethod._0;
  }
  switch (requestMethod) {
    case "Get" :
      return "GET";
    case "Head" :
      return "HEAD";
    case "Post" :
      return "POST";
    case "Put" :
      return "PUT";
    case "Delete" :
      return "DELETE";
    case "Connect" :
      return "CONNECT";
    case "Options" :
      return "OPTIONS";
    case "Trace" :
      return "TRACE";
    case "Patch" :
      return "PATCH";
  }
}

let AbortController = {};

function encodeReferrerPolicy(referrerPolicy) {
  switch (referrerPolicy) {
    case "None" :
      return "";
    case "NoReferrer" :
      return "no-referrer";
    case "NoReferrerWhenDowngrade" :
      return "no-referrer-when-downgrade";
    case "SameOrigin" :
      return "same-origin";
    case "Origin" :
      return "origin";
    case "StrictOrigin" :
      return "strict-origin";
    case "OriginWhenCrossOrigin" :
      return "origin-when-cross-origin";
    case "StrictOriginWhenCrossOrigin" :
      return "strict-origin-when-cross-origin";
    case "UnsafeUrl" :
      return "unsafe-url";
  }
}

let UnknownReferrerPolicy = /* @__PURE__ */Primitive_exceptions.create("Fetch.UnknownReferrerPolicy");

let UnknownRequestType = /* @__PURE__ */Primitive_exceptions.create("Fetch.UnknownRequestType");

let UnknownRequestDestination = /* @__PURE__ */Primitive_exceptions.create("Fetch.UnknownRequestDestination");

function encodeRequestMode(requestMode) {
  switch (requestMode) {
    case "Navigate" :
      return "navigate";
    case "SameOrigin" :
      return "same-origin";
    case "NoCORS" :
      return "no-cors";
    case "CORS" :
      return "cors";
  }
}

let UnknownRequestMode = /* @__PURE__ */Primitive_exceptions.create("Fetch.UnknownRequestMode");

function encodeRequestCredentials(requestCredentials) {
  switch (requestCredentials) {
    case "Omit" :
      return "omit";
    case "SameOrigin" :
      return "same-origin";
    case "Include" :
      return "include";
  }
}

let UnknownRequestCredentials = /* @__PURE__ */Primitive_exceptions.create("Fetch.UnknownRequestCredentials");

function encodeRequestCache(requestCache) {
  switch (requestCache) {
    case "Default" :
      return "default";
    case "NoStore" :
      return "no-store";
    case "Reload" :
      return "reload";
    case "NoCache" :
      return "no-cache";
    case "ForceCache" :
      return "force-cache";
    case "OnlyIfCached" :
      return "only-if-cached";
  }
}

let UnknownRequestCache = /* @__PURE__ */Primitive_exceptions.create("Fetch.UnknownRequestCache");

function encodeRequestRedirect(requestRedirect) {
  switch (requestRedirect) {
    case "Follow" :
      return "follow";
    case "Error" :
      return "error";
    case "Manual" :
      return "manual";
  }
}

let UnknownRequestRedirect = /* @__PURE__ */Primitive_exceptions.create("Fetch.UnknownRequestRedirect");

let HeadersInit = {};

let Headers = {};

let BodyInit = {};

let Body = {};

function make(method_, headers, body, referrer, referrerPolicy, mode, credentials, cache, redirect, integrity, keepalive, signal, param) {
  let tmp = {};
  let tmp$1 = Stdlib_Option.map(method_, encodeRequestMethod);
  if (tmp$1 !== undefined) {
    tmp.method = tmp$1;
  }
  if (headers !== undefined) {
    tmp.headers = Primitive_option.valFromOption(headers);
  }
  if (body !== undefined) {
    tmp.body = Primitive_option.valFromOption(body);
  }
  if (referrer !== undefined) {
    tmp.referrer = referrer;
  }
  let tmp$2 = Stdlib_Option.map(referrerPolicy, encodeReferrerPolicy);
  if (tmp$2 !== undefined) {
    tmp.referrerPolicy = tmp$2;
  }
  let tmp$3 = Stdlib_Option.map(mode, encodeRequestMode);
  if (tmp$3 !== undefined) {
    tmp.mode = tmp$3;
  }
  let tmp$4 = Stdlib_Option.map(credentials, encodeRequestCredentials);
  if (tmp$4 !== undefined) {
    tmp.credentials = tmp$4;
  }
  let tmp$5 = Stdlib_Option.map(cache, encodeRequestCache);
  if (tmp$5 !== undefined) {
    tmp.cache = tmp$5;
  }
  let tmp$6 = Stdlib_Option.map(redirect, encodeRequestRedirect);
  if (tmp$6 !== undefined) {
    tmp.redirect = tmp$6;
  }
  if (integrity !== undefined) {
    tmp.integrity = integrity;
  }
  if (keepalive !== undefined) {
    tmp.keepalive = keepalive;
  }
  if (signal !== undefined) {
    tmp.signal = Primitive_option.valFromOption(signal);
  }
  return tmp;
}

let RequestInit = {
  make: make
};

function method_(self) {
  let requestMethod = self.method;
  switch (requestMethod) {
    case "CONNECT" :
      return "Connect";
    case "DELETE" :
      return "Delete";
    case "GET" :
      return "Get";
    case "HEAD" :
      return "Head";
    case "OPTIONS" :
      return "Options";
    case "PATCH" :
      return "Patch";
    case "POST" :
      return "Post";
    case "PUT" :
      return "Put";
    case "TRACE" :
      return "Trace";
    default:
      return {
        TAG: "Other",
        _0: requestMethod
      };
  }
}

function type_(self) {
  let requestType = self.type;
  switch (requestType) {
    case "" :
      return "None";
    case "audio" :
      return "Audio";
    case "font" :
      return "Font";
    case "image" :
      return "Image";
    case "script" :
      return "Script";
    case "style" :
      return "Style";
    case "track" :
      return "Track";
    case "video" :
      return "Video";
    default:
      throw {
        RE_EXN_ID: UnknownRequestType,
        _1: requestType,
        Error: new Error()
      };
  }
}

function destination(self) {
  let requestDestination = self.destination;
  switch (requestDestination) {
    case "" :
      return "None";
    case "document" :
      return "Document";
    case "embed" :
      return "Embed";
    case "font" :
      return "Font";
    case "image" :
      return "Image";
    case "manifest" :
      return "Manifest";
    case "media" :
      return "Media";
    case "object" :
      return "Object";
    case "report" :
      return "Report";
    case "script" :
      return "Script";
    case "serviceworker" :
      return "ServiceWorker";
    case "sharedworker" :
      return "SharedWorker";
    case "style" :
      return "Style";
    case "worker" :
      return "Worker";
    case "xslt" :
      return "Xslt";
    default:
      throw {
        RE_EXN_ID: UnknownRequestDestination,
        _1: requestDestination,
        Error: new Error()
      };
  }
}

function referrerPolicy(self) {
  let referrerPolicy$1 = self.referrerPolicy;
  switch (referrerPolicy$1) {
    case "" :
      return "None";
    case "no-referrer" :
      return "NoReferrer";
    case "no-referrer-when-downgrade" :
      return "NoReferrerWhenDowngrade";
    case "origin" :
      return "Origin";
    case "origin-when-cross-origin" :
      return "OriginWhenCrossOrigin";
    case "same-origin" :
      return "SameOrigin";
    case "strict-origin" :
      return "StrictOrigin";
    case "strict-origin-when-cross-origin" :
      return "StrictOriginWhenCrossOrigin";
    case "unsafe-url" :
      return "UnsafeUrl";
    default:
      throw {
        RE_EXN_ID: UnknownReferrerPolicy,
        _1: referrerPolicy$1,
        Error: new Error()
      };
  }
}

function mode(self) {
  let requestMode = self.mode;
  switch (requestMode) {
    case "cors" :
      return "CORS";
    case "navigate" :
      return "Navigate";
    case "no-cors" :
      return "NoCORS";
    case "same-origin" :
      return "SameOrigin";
    default:
      throw {
        RE_EXN_ID: UnknownRequestMode,
        _1: requestMode,
        Error: new Error()
      };
  }
}

function credentials(self) {
  let requestCredentials = self.credentials;
  switch (requestCredentials) {
    case "include" :
      return "Include";
    case "omit" :
      return "Omit";
    case "same-origin" :
      return "SameOrigin";
    default:
      throw {
        RE_EXN_ID: UnknownRequestCredentials,
        _1: requestCredentials,
        Error: new Error()
      };
  }
}

function cache(self) {
  let requestCache = self.cache;
  switch (requestCache) {
    case "default" :
      return "Default";
    case "force-cache" :
      return "ForceCache";
    case "no-cache" :
      return "NoCache";
    case "no-store" :
      return "NoStore";
    case "only-if-cached" :
      return "OnlyIfCached";
    case "reload" :
      return "Reload";
    default:
      throw {
        RE_EXN_ID: UnknownRequestCache,
        _1: requestCache,
        Error: new Error()
      };
  }
}

function redirect(self) {
  let requestRedirect = self.redirect;
  switch (requestRedirect) {
    case "error" :
      return "Error";
    case "follow" :
      return "Follow";
    case "manual" :
      return "Manual";
    default:
      throw {
        RE_EXN_ID: UnknownRequestRedirect,
        _1: requestRedirect,
        Error: new Error()
      };
  }
}

let Request = {
  method_: method_,
  type_: type_,
  destination: destination,
  referrerPolicy: referrerPolicy,
  mode: mode,
  credentials: credentials,
  cache: cache,
  redirect: redirect
};

let Response = {};

exports.AbortController = AbortController;
exports.HeadersInit = HeadersInit;
exports.Headers = Headers;
exports.BodyInit = BodyInit;
exports.Body = Body;
exports.RequestInit = RequestInit;
exports.Request = Request;
exports.Response = Response;
/* No side effect */
