// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("rescript-test/src/Test.res.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Core__Option = require("@rescript/core/src/Core__Option.res.js");
var Client = require("react-dom/client");
var Webapi__Dom__Document = require("rescript-webapi/src/Webapi/Dom/Webapi__Dom__Document.res.js");

function createContainer() {
  var containerElement = document.createElement("div");
  containerElement.setAttribute("id", "test");
  Core__Option.map(Webapi__Dom__Document.asHtmlDocument(document), (function (htmlDocument) {
          Core__Option.forEach(Caml_option.nullable_to_opt(htmlDocument.body), (function (body) {
                  body.appendChild(containerElement);
                }));
        }));
  return Client.createRoot(containerElement);
}

function cleanupContainer(container) {
  var containerElement = document.querySelector("#test");
  if (!(containerElement == null)) {
    containerElement.remove();
  }
  container.unmount();
}

function testWithReact(extra, extra$1) {
  return Test.testWith(createContainer, cleanupContainer, extra, extra$1);
}

function testAsyncWithReact(extra, extra$1, extra$2) {
  return Test.testAsyncWith(createContainer, cleanupContainer, extra, extra$1, extra$2);
}

exports.createContainer = createContainer;
exports.cleanupContainer = cleanupContainer;
exports.testWithReact = testWithReact;
exports.testAsyncWithReact = testAsyncWithReact;
/* Test Not a pure module */
